### ISSUE TITLE
Tests for SecretStore service contract

### ISSUE THREAD

**Issue by rphmeier** [paritytech/contracts#100]
The actual behavior of the contract is not yet fully determined, so when it is, the tests should be added.

**Comment by svyatonik** [comment]
Was trying to fix this today, on top of #102, but looks like it is impossible right now. The problem is that:
1) Service contract waits for signatures of authorities in its `serverKeyGenerated` method
2) this signature (right now) differs from the signature generated by `eth_sign` RPC
3) to generate correct signature I need the private key of authority + ECDSA JS library

What I think of it, is that I should possibly switch to the `eth_sign` compatible signatures in this particular contract. Previously didn't wanted to mess with different signing methods (everywhere else in SS I use signatures without prefixes). Will do this after at least half of active 7 SS-related PRs will be reviewed

**Comment by svyatonik** [comment]
https://github.com/parity-contracts/secretstore-service/pull/1
