### ISSUE TITLE
Wallet: Change for token transfers allows daily limit bypass

### ISSUE THREAD

**Issue by barryWhiteHat** [paritytech/contracts#38]
I am a little worried about the change to wallet.sol.
[`if ((_data.length == 0 && underLimit(_value)) || m_required == 1) {`](https://github.com/ethcore/contracts/blob/master/Wallet.sol#L341)

I think that this change allows someone can bypass the daily Limit by just including data in the transaction. The call will still work if the recipient is a non contract address.

So someone could use this to empty a multisig that holds 100 ETH and has a 1 ETH per day limit in a single day.

**Comment by gavofyork** [comment]
i think you're misinterpreting the logic.

> if (there is no data) AND (the transaction doesn't cross the daily limit)

this means you need to BOTH have no data and respect the daily limit. you can't get around the daily limit by including data - indeed by including data, the daily limit stops applying.

**Comment by branciard** [comment]
Hi, 
is the order chosen :
`if (there is no data) AND (the transaction doesn't cross the daily limit)`
vs
`if (the transaction doesn't cross the daily limit) AND  (there is no data) `
intentional ?
Results will differ.
I had a log event in underLimit function to see when it is called or not called.
see tests here between both cases :  
https://github.com/branciard/multisigundertests/blob/master/test/wallet.js#L360
https://github.com/branciard/multisigundertests/blob/master/test/wallet.js#L416

See also https://github.com/paritytech/contracts/issues/72 , i open this issue before discovering this one.
